source 'https://supermarket.chef.io'
source 'https://supermarket.company.com'

solver :ruby

metadata

cookbook 'apache', git: 'https://git.company.com/apache/cookbook-apache', branch: 'v7_apache_secure_setup'
cookbook 'NessusAgent', git: 'https://git.company.com/SecurityDept/NessusAgent'
cookbook 'node_setup', '3.0.10'
