=====================================================
CONTAINER TO JUST HOST SSHD TO SSH INTO THE CONTAINER
=====================================================
https://docs.docker.com/engine/examples/running_ssh_service/

========================
DOCKERFILE
========================
#FROM ubuntu:14.04 --> 14.04 root password change is not working
#FROM ubuntu
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:linux123' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]


==========================
BUILD
==========================
NOTE: eg_sshd is the image name

$ docker build -t eg_sshd .

==========================
RUN
==========================
- Create the container test_sshd with port forwarding (-P) and as a daemon (-d)
$ docker run -d -P --name test_sshd eg_sshd

- Check the forwarded port
$ docker port test_sshd 22

==========================
CONNECT
==========================
$ ssh root@172.17.0.3
password: < password set in Dockerfile for root >

$ ssh root@localhost -p <forward port name>
password:
