Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vm|
      vm.memory = 2560
      vm.name = "cassandra-centos7-from-model"
  end

  #config.vm.box = "centos/7"
  #config.vm.box_download_insecure = "centos/7"
  config.vm.box = "cassandra311-centos7-model"

  config.vm.hostname = "cassandra-from-model"
  config.vm.network "private_network", ip: "193.168.3.101"

  #config.ssh.password = "vagrant"

end
