Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vm|
      vm.memory = 2560
      vm.name = "cassandra-centos7-model"
  end

  # Initially used this box - from web, without guest additions
  #config.vm.box = "centos/7"
  #config.vm.box_download_insecure = "centos/7"
  
  # Later used this box with guest additions
  config.vm.box  = "centos-7-web-added-guest-add"

  config.vm.hostname = "cassandra-model"
  config.vm.network "private_network", ip: "193.168.3.100"

end
